name: Update API Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install python-dotenv openai

    - name: Generate OpenAPI documentation
      env:
        TOKEN_4o: ${{ secrets.TOKEN_4o }}  # Pass the secret as an environment variable
      run: python utils/openapi_generator.py

    - name: Commit and push changes
      run: |
        git config user.name "Bharadwajreddy1406"
        git config user.email "bharadwajreddy146@gmail.com"
        git add openapi.json
        git commit -m "Update API documentation"
        git push origin gh-pages
