name: Deploy API Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install python-dotenv openai

    - name: Generate API documentation
      env:
        TOKEN_4O: ${{ secrets.TOKEN_4O }}
      run: python -m utils.openapi_generator

    - name: Deploy to gh-pages
      run: |
        git config user.name "Bharadwajreddy1406"
        git config user.email "bharadwajreddy146@gmail.com"
        git checkout -b gh-pages || git checkout gh-pages
        mv index.html openapi.json .
        git add index.html openapi.json
        git commit -m "Deploy API documentation"
        git push origin gh-pages --force
