name: Update API Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install python-dotenv openai

    - name: Debug current branch and files
      run: |
        echo "Current branch and files:"
        git branch
        ls -R

    - name: Generate OpenAPI documentation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python -m utils.openapi_generator

    - name: Commit and push changes to gh-pages
      run: |
        git config user.name "Bharadwajreddy1406"
        git config user.email "bharadwajreddy146@gmail.com"
        # Ensure the gh-pages branch exists
        git checkout -b gh-pages || git checkout gh-pages
        git add openapi.json
        git commit -m "Update API documentation" || echo "No changes to commit"
        git push origin gh-pages --force

    - name: Verify pushed changes
      run: |
        echo "Verify gh-pages branch content:"
        git log --oneline
